// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxt6xlVkyLNSFkFAMLDjyzenzbu2k7tfc',
    appId: '1:732422651778:web:1391b2f7f2aeef6e2b599b',
    messagingSenderId: '732422651778',
    projectId: 'notes-app-85c53',
    authDomain: 'notes-app-85c53.firebaseapp.com',
    storageBucket: 'notes-app-85c53.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf6XcAp4oU5oPTeucCnPtP7NMobo5nQA0',
    appId: '1:732422651778:android:c383bc442d86ff702b599b',
    messagingSenderId: '732422651778',
    projectId: 'notes-app-85c53',
    storageBucket: 'notes-app-85c53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrsMt6MoWaJXQHINPkwSpv_E7KvbQfnF0',
    appId: '1:732422651778:ios:456c7e724747fde82b599b',
    messagingSenderId: '732422651778',
    projectId: 'notes-app-85c53',
    storageBucket: 'notes-app-85c53.firebasestorage.app',
    iosBundleId: 'com.example.notesApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrsMt6MoWaJXQHINPkwSpv_E7KvbQfnF0',
    appId: '1:732422651778:ios:456c7e724747fde82b599b',
    messagingSenderId: '732422651778',
    projectId: 'notes-app-85c53',
    storageBucket: 'notes-app-85c53.firebasestorage.app',
    iosBundleId: 'com.example.notesApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxt6xlVkyLNSFkFAMLDjyzenzbu2k7tfc',
    appId: '1:732422651778:web:672f76637ddb21112b599b',
    messagingSenderId: '732422651778',
    projectId: 'notes-app-85c53',
    authDomain: 'notes-app-85c53.firebaseapp.com',
    storageBucket: 'notes-app-85c53.firebasestorage.app',
  );
}
